<?php
declare(strict_types=1);

namespace App\View\Helper;

use Cake\View\Helper;
use Cake\View\View;

/**
 * Auth helper
 */
class AuthHelper extends Helper
{
    /**
     * Default configuration.
     *
     * @var array<string, mixed>
     */
    protected $_defaultConfig = [];

    function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

//        pr ('AuthHelper - init');
//        dd ($this->request);
    }

//    public function beforeRender(EventInterface $event, $viewFile) {
//           //reqest can then inject data into
//        // //$this->>getView->set
//
//        //$this->getView()->
//    }
    function isLoggedIn() {
        $req = $this->getView()->getRequest();
        //dd($req);
        if ($req->getAttribute('access') == true) {
            return true;
        }
        return false;
    }

}


