<?php
declare(strict_types=1);

namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Model\Table\EmailQueuesTable;
use Cake\Event\EventInterface;
use Cake\Routing\Router;

/**
 * Staff-only email queue management: list, create, edit, send, and
 * soft-remove queued emails. See docs/features/email-queue-feature.md.
 */
class EmailQueuesController extends AppController
{
    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $tab = $this->request->getQuery('tab') === 'sent' ? 'sent' : 'waiting';
        $this->set('activeTab', $tab);

        $rows = $this->EmailQueues->find()
            ->contain(['Users'])
            ->where([
                'EmailQueues.removed' => false,
                'EmailQueues.sent' => $tab === 'sent',
            ])
            ->orderDesc('EmailQueues.id')
            ->all();

        $this->set('rows', $this->EmailQueues->decorateStatus($rows));
    }

    public function create()
    {
        $entity = $this->EmailQueues->newEmptyEntity();

        if ($this->request->is('post')) {
            $data = $this->request->getData();
            $uploads = $this->request->getUploadedFiles()['attachments'] ?? [];

            $result = $this->EmailQueues->queueEmail(
                (string)($data['email_to'] ?? ''),
                (string)($data['subject'] ?? ''),
                (string)($data['body'] ?? ''),
                [
                    'user_id' => $this->getUserId(),
                    'email_from' => $data['email_from'] ?? EmailQueuesTable::DEFAULT_FROM,
                    'cc' => $data['cc'] ?? null,
                    'bcc' => $data['bcc'] ?? null,
                    'language' => $data['language'] ?? 'en',
                    'attachments' => $uploads,
                ]
            );

            if ($result['STATUS'] === 200) {
                $this->Flash->success($result['MSG']);

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error($result['MSG']);
        }

        $this->set('entity', $entity);
        $this->set('fromOptions', EmailQueuesTable::FROM_OPTIONS);
        $this->set('defaultFrom', EmailQueuesTable::DEFAULT_FROM);
    }

    public function edit($id)
    {
        $entity = $this->EmailQueues->get($id, ['contain' => ['EmailQueueAttachments', 'Users']]);

        if ($this->request->is(['post', 'put', 'patch'])) {
            $this->edit_save($entity);

            return $this->redirect(['action' => 'index']);
        }

        $this->set('entity', $entity);
        $this->set('fromOptions', EmailQueuesTable::FROM_OPTIONS);
        $this->set('defaultFrom', EmailQueuesTable::DEFAULT_FROM);
    }

    private function edit_save($entity): void
    {
        $data = $this->request->getData();
        $entity = $this->EmailQueues->patchEntity($entity, [
            'email_to' => $data['email_to'] ?? '',
            'email_from' => $data['email_from'] ?? EmailQueuesTable::DEFAULT_FROM,
            'cc' => $data['cc'] ?? null,
            'bcc' => $data['bcc'] ?? null,
            'subject' => $data['subject'] ?? '',
            'body' => $data['body'] ?? '',
            'language' => $data['language'] ?? 'en',
        ]);

        if (!$this->EmailQueues->save($entity)) {
            $this->Flash->error('Email could not be updated');

            return;
        }

        $uploads = $this->request->getUploadedFiles()['attachments'] ?? [];
        $this->EmailQueues->attachFiles((int)$entity->id, $uploads);
        $this->Flash->success('Email updated');
    }

    public function send($id)
    {
        $result = $this->EmailQueues->send((int)$id, true);
        $this->flashResult($result, 'Email sent!');

        return $this->redirect($this->referer(['action' => 'index']));
    }

    public function sendTest($id)
    {
        $result = $this->EmailQueues->send((int)$id, false);
        $this->flashResult($result, 'Test email sent (not marked as sent)');

        return $this->redirect($this->referer(['action' => 'index']));
    }

    private function flashResult(array $result, string $successMessage): void
    {
        if ($result['STATUS'] === 200) {
            $this->Flash->success($successMessage);
        } else {
            $this->Flash->error($result['MSG']);
        }
    }

    public function sendAll()
    {
        $result = $this->EmailQueues->sendAll(true);
        $this->Flash->success("Sent {$result['sent']} of {$result['total']} queued email(s).");

        return $this->redirect($this->referer(['action' => 'index']));
    }

    public function sendAllTest()
    {
        $result = $this->EmailQueues->sendAll(false);
        $this->Flash->success("Test-sent {$result['sent']} of {$result['total']} queued email(s).");

        return $this->redirect($this->referer(['action' => 'index']));
    }

    public function remove($id)
    {
        $result = $this->EmailQueues->remove((int)$id);
        $result['STATUS'] === 200 ? $this->Flash->success($result['MSG']) : $this->Flash->error($result['MSG']);

        return $this->redirect($this->referer(['action' => 'index']));
    }

    public function removeAll()
    {
        $this->EmailQueues->removeAll();
        $this->Flash->success('Waiting emails removed.');

        return $this->redirect($this->referer(['action' => 'index']));
    }
}
